apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdg-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdg
      tier: backend
  template:
    metadata:
      labels:
        app: mdg
        tier: backend
    spec:
      containers:
        - name: backend
          image: mdg-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
