apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdg-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdg
      tier: cache
  template:
    metadata:
      labels: 
        app: mdg
        tier: cache
    spec:
      containers:
      - name: redis
        image: redis:5.0
        ports:
          - containerPort: 6379
