apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mdg-frontend
spec:
  selector:
    matchLabels:
      app: mdg
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels: 
        app: mdg
        tier: frontend
    spec:
      containers: 
        - name: nginx
          image: mdg-frontend
          imagePullPolicy: Never
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          ports:
            - containerPort: 3000